<?php
// +--------------------------------------------------------------------------+
// |							Kshop
// | 							Module for Xoops
// |            				www.kaotik.biz
// |            				kaotik1@gmail.com
// +--------------------------------------------------------------------------+

$modversion['name'] = "Kshop";
$modversion['version'] = 2.23;
$modversion['description'] = "A commerce module for Xoops. Visit www.kaotik.biz for more info.";
$modversion['credits'] = "kaotik";
$modversion['help'] = "help.htm";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/kshop_slogo.png";
$modversion['dirname'] = "kshop";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "kshop_categories";
$modversion['tables'][1] = "kshop_products";
$modversion['tables'][2] = "kshop_products_categories";
$modversion['tables'][3] = "kshop_users";
$modversion['tables'][4] = "kshop_options";
$modversion['tables'][5] = "kshop_products_options";
$modversion['tables'][6] = "kshop_plugins";
$modversion['tables'][7] = "kshop_orders";
$modversion['tables'][8] = "kshop_orders_products";
$modversion['tables'][9] = "kshop_country";
$modversion['tables'][10] = "kshop_orders_status";
$modversion['tables'][11] = "kshop_orders_users";
$modversion['tables'][12] = "kshop_status";
$modversion['tables'][13] = "kshop_text";
$modversion['tables'][14] = "kshop_products_brands";
$modversion['tables'][15] = "kshop_brands";


// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";


// Menu
global $xoopsUser;
$modversion['hasMain'] = 1;
if(is_object($xoopsUser)){
$modversion['sub'][1]['name'] = _KS_MAINMYORDS;
$modversion['sub'][1]['url'] = "myorders.php";
}

//Uninstall plugin tables
$modversion['onUninstall'] = 'install_funcs.php';

//Comments
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'id';
$modversion['comments']['pageName'] = 'product_details.php';

//Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "search.php";
$modversion['search']['func'] = "search_kshop";

//////////////////////////////////////////////////////////////////
// Templates
$modversion['templates'][1]['file'] = 'ks_send_mail.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'ks_main_header.html';
$modversion['templates'][2]['description'] = 'Main menu header'; 
$modversion['templates'][4]['file'] = 'ks_specials.html';
$modversion['templates'][4]['description'] = 'Specials at the end of main page'; 
$modversion['templates'][5]['file'] = 'ks_prod_details.html';
$modversion['templates'][5]['description'] = 'Product details'; 
$modversion['templates'][10]['file'] = 'ks_main_body.html';
$modversion['templates'][10]['description'] = 'Body of main page'; 
$modversion['templates'][11]['file'] = 'ks_cart.html';
$modversion['templates'][11]['description'] = 'Shopping cart template';
$modversion['templates'][12]['file'] = 'admin_smartytest.html';
$modversion['templates'][12]['description'] = 'Body of main page'; 
$modversion['templates'][13]['file'] = 'ks_addtocart.html';
$modversion['templates'][13]['description'] = 'Add to cart page'; 
$modversion['templates'][14]['file'] = 'ks_checkout_header.html';
$modversion['templates'][14]['description'] = 'Checkout header which shows the various steps'; 
$modversion['templates'][15]['file'] = 'ks_checkout_step1.html';
$modversion['templates'][15]['description'] = 'First step in checkout process. Where users inputs info'; 
$modversion['templates'][16]['file'] = 'ks_checkout_step2.html';
$modversion['templates'][16]['description'] = 'second step where user choose payment'; 
$modversion['templates'][17]['file'] = 'ks_checkout_step3.html';
$modversion['templates'][17]['description'] = 'third step where user chooses shipping'; 
$modversion['templates'][18]['file'] = 'ks_checkout_step4.html';
$modversion['templates'][18]['description'] = 'Confirmation page, last step in checkout'; 
$modversion['templates'][19]['file'] = 'ks_checkout_step5.html';
$modversion['templates'][19]['description'] = 'Process checkout, send email, save order clients details, etc'; 
$modversion['templates'][50]['file'] = 'ks_myorders_details.html';
$modversion['templates'][50]['description'] = 'Details of past orders'; 
$modversion['templates'][51]['file'] = 'ks_myorders.html';
$modversion['templates'][51]['description'] = 'past orders for each user'; 
$modversion['templates'][52]['file'] = 'ks_search.html';
$modversion['templates'][52]['description'] = 'Search only in kshop template'; 


//Admin Templates
$modversion['templates'][20]['file'] = 'admin_textarea.html';
$modversion['templates'][20]['description'] = 'Text Area'; 
$modversion['templates'][21]['file'] = 'admin_products.html';
$modversion['templates'][21]['description'] = 'Products'; 
$modversion['templates'][22]['file'] = 'admin_products_list.html';
$modversion['templates'][22]['description'] = 'Products List'; 
$modversion['templates'][23]['file'] = 'admin_options.html';
$modversion['templates'][23]['description'] = 'Create and Delete options'; 
$modversion['templates'][24]['file'] = 'admin_category_list.html';
$modversion['templates'][24]['description'] = 'List all categories'; 
$modversion['templates'][25]['file'] = 'admin_category.html';
$modversion['templates'][25]['description'] = 'Edit or insert new category form'; 
$modversion['templates'][26]['file'] = 'admin_orders_details.html';
$modversion['templates'][26]['description'] = 'Details of orders'; 
$modversion['templates'][27]['file'] = 'admin_main.html';
$modversion['templates'][27]['description'] = 'Template for index page'; 
$modversion['templates'][28]['file'] = 'admin_orders.html';
$modversion['templates'][28]['description'] = 'List orders'; 
$modversion['templates'][29]['file'] = 'admin_xajax_plugins.html';
$modversion['templates'][29]['description'] = 'Xajax plugin template'; 
$modversion['templates'][30]['file'] = 'admin_plugins.html';
$modversion['templates'][30]['description'] = 'Plugins template'; 
$modversion['templates'][31]['file'] = 'admin_order_status.html';
$modversion['templates'][31]['description'] = 'Order status template'; 
$modversion['templates'][32]['file'] = 'admin_brands.html';
$modversion['templates'][32]['description'] = 'Template to insert or change brands'; 
$modversion['templates'][33]['file'] = 'admin_xajax_add_status.html';
$modversion['templates'][33]['description'] = 'Form to add a new status'; 


// Blocks
$modversion['blocks'][1]['file'] = "shopping_cart.php";
$modversion['blocks'][1]['name'] = 'Kshop Shopping Cart';
$modversion['blocks'][1]['description'] = 'Displays the shopping cart as a block';
$modversion['blocks'][1]['show_func'] = "shopping_cart";
$modversion['blocks'][1]['template'] = 'shopping_cart.html';

$modversion['blocks'][2]['file'] = "shop_categories.php";
$modversion['blocks'][2]['name'] = 'Kshop Categories';
$modversion['blocks'][2]['description'] = 'Displays he various shop categories and subcategories';
$modversion['blocks'][2]['show_func'] = "shop_categories";
$modversion['blocks'][2]['template'] = 'shop_cat.html';

$modversion['blocks'][3]['file'] = "products.php";
$modversion['blocks'][3]['name'] = 'Kshop Random Products';
$modversion['blocks'][3]['description'] = 'Display random products';
$modversion['blocks'][3]['show_func'] = "random_products";
$modversion['blocks'][3]['edit_func'] = "random_products_edit";
$modversion['blocks'][3]['template'] = 'random_products.html';
$modversion['blocks'][3]['options'] = '1|4|2|0';

$modversion['blocks'][4]['file'] = "brands.php";
$modversion['blocks'][4]['name'] = 'Kshop Brands';
$modversion['blocks'][4]['description'] = 'Display brands';
$modversion['blocks'][4]['show_func'] = "ks_brands";
$modversion['blocks'][4]['template'] = 'ks_brands.html';



// Config categories
$modversion['configcat'][1]['nameid'] = 'settings';
$modversion['configcat'][1]['name'] = '_KSHOP_CAT_SETTINGS';
$modversion['configcat'][1]['description'] = '_KSHOP_CAT_SETTINGS_DSC';

$modversion['configcat'][2]['nameid'] = 'payment';
$modversion['configcat'][2]['name'] = '_KSHOP_CAT_PAYMENT';
$modversion['configcat'][2]['description'] = '_KSHOP_CAT_PAYMENT_DSC';

$modversion['configcat'][3]['nameid'] = 'required';
$modversion['configcat'][3]['name'] = '_KSHOP_CAT_REQUIRED';
$modversion['configcat'][3]['description'] = '_KSHOP_CAT_REQUIRED_DSC';

$modversion['configcat'][4]['nameid'] = 'layout';
$modversion['configcat'][4]['name'] = '_KSHOP_CAT_LAYOUT';
$modversion['configcat'][4]['description'] = '_KSHOP_CAT_LAYOUT_DSC';



//Preferences
$i=1;
$modversion['config'][$i]['name'] = 'debug';
$modversion['config'][$i]['title'] = '_KS_DEBUG';
$modversion['config'][$i]['description'] = '_KS_DEBUGDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$modversion['config'][$i]['category'] = 'settings';
$i++;
$modversion['config'][$i]['name'] = 'shopname';
$modversion['config'][$i]['title'] = '_KS_SHOPNAME';
$modversion['config'][$i]['description'] = '_KS_SHOPNAMEDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'Kshop';
$modversion['config'][$i]['category'] = 'settings';
$i++;
$modversion['config'][$i]['name'] = 'slogan';
$modversion['config'][$i]['title'] = '_KS_SLOGAN';
$modversion['config'][$i]['description'] = '_KS_SLOGANDESC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'Welcome to the freshest grocery store on the internet!';
$modversion['config'][$i]['category'] = 'settings';
$i++;
$modversion['config'][$i]['name'] = 'subjectline';
$modversion['config'][$i]['title'] = '_KS_SUBJECTLINE';
$modversion['config'][$i]['description'] = '_KS_SUBJECTLINEDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'Order from your store';
$modversion['config'][$i]['category'] = 'settings';
$i++;
$modversion['config'][$i]['name'] = 'mailorder';
$modversion['config'][$i]['title'] = '_KS_MAILORDER';
$modversion['config'][$i]['description'] = '_KS_MAILORDERDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'shoporder@your_shop.com';
$modversion['config'][$i]['category'] = 'settings';
$i++;
$modversion['config'][$i]['name'] = 'mailcontact';
$modversion['config'][$i]['title'] = '_KS_MAILCONTACT';
$modversion['config'][$i]['description'] = '_KS_MAILCONTACTDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'contact@your_shop.com';
$modversion['config'][$i]['category'] = 'settings';
$i++;
$modversion['config'][$i]['name'] = 'defcountry';
$modversion['config'][$i]['title'] = '_KS_DEFCOUNTRY';
$modversion['config'][$i]['description'] = '_KS_DEFCOUNTRYDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'Liechtenstein';
$modversion['config'][$i]['category'] = 'settings';
$i++;
$modversion['config'][$i]['name'] = 'currency';
$modversion['config'][$i]['title'] = '_KS_CURRENCY';
$modversion['config'][$i]['description'] = '_KS_CURRENCYDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'EUR';
$modversion['config'][$i]['category'] = 'payment';
$i++;
$modversion['config'][$i]['name'] = 'currencyfirst';
$modversion['config'][$i]['title'] = '_KS_CURRENCYFIRST';
$modversion['config'][$i]['description'] = '_KS_CURRENCYFIRSTDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$modversion['config'][$i]['category'] = 'payment';
$i++;
$modversion['config'][$i]['name'] = 'decimal';
$modversion['config'][$i]['title'] = '_KS_DECHOU';
$modversion['config'][$i]['description'] = '_KS_DECHOUDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 2;
$modversion['config'][$i]['category'] = 'payment';
$i++;
$modversion['config'][$i]['name'] = 'minorder';
$modversion['config'][$i]['title'] = '_KS_MINORDER';
$modversion['config'][$i]['description'] = '_KS_MINORDDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$modversion['config'][$i]['category'] = 'payment';
$i++;
$modversion['config'][$i]['name'] = 'globaltax';
$modversion['config'][$i]['title'] = '_KS_GLOBALTAX';
$modversion['config'][$i]['description'] = '_KS_GLOBALTAXDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 5;
$modversion['config'][$i]['category'] = 'payment';
$i++;
$modversion['config'][$i]['name'] = 'incotplugs';
$modversion['config'][$i]['title'] = '_KS_INCOTPLUGS';
$modversion['config'][$i]['description'] = '_KS_INCOTPLUGSDESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$modversion['config'][$i]['category'] = 'payment';


$i++;
//Required Fields
$modversion['config'][$i]['name'] = 'reqfirstname';
$modversion['config'][$i]['title'] = '_KS_REQFIRSTNAME';
$modversion['config'][$i]['description'] = '_KS_REQFIRSTNAMEDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$modversion['config'][$i]['category'] = 'required';
$i++;
$modversion['config'][$i]['name'] = 'reqlastname';
$modversion['config'][$i]['title'] = '_KS_REQLASTNAME';
$modversion['config'][$i]['description'] = '_KS_REQLASTNAMEDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$modversion['config'][$i]['category'] = 'required';
$i++;
$modversion['config'][$i]['name'] = 'reqcompany';
$modversion['config'][$i]['title'] = '_KS_REQCOMPANY';
$modversion['config'][$i]['description'] = '_KS_REQCOMPANYDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$modversion['config'][$i]['category'] = 'required';
$i++;
$modversion['config'][$i]['name'] = 'reqstreet';
$modversion['config'][$i]['title'] = '_KS_REQSTREET';
$modversion['config'][$i]['description'] = '_KS_REQSTREETDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$modversion['config'][$i]['category'] = 'required';
$i++;
$modversion['config'][$i]['name'] = 'reqzip';
$modversion['config'][$i]['title'] = '_KS_REQZIP';
$modversion['config'][$i]['description'] = '_KS_REQZIPDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$modversion['config'][$i]['category'] = 'required';
$i++;
$modversion['config'][$i]['name'] = 'reqcity';
$modversion['config'][$i]['title'] = '_KS_REQCITY';
$modversion['config'][$i]['description'] = '_KS_REQCITYDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$modversion['config'][$i]['category'] = 'required';
$i++;
$modversion['config'][$i]['name'] = 'reqcountry';
$modversion['config'][$i]['title'] = '_KS_REQCOUNTRY';
$modversion['config'][$i]['description'] = '_KS_REQCOUNTRYDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$modversion['config'][$i]['category'] = 'required';
$i++;
$modversion['config'][$i]['name'] = 'reqtelefone';
$modversion['config'][$i]['title'] = '_KS_REQTELEFONE';
$modversion['config'][$i]['description'] = '_KS_REQTELEFONEDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$modversion['config'][$i]['category'] = 'required';
$i++;
$modversion['config'][$i]['name'] = 'reqfax';
$modversion['config'][$i]['title'] = '_KS_REQFAX';
$modversion['config'][$i]['description'] = '_KS_REQFAXDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$modversion['config'][$i]['category'] = 'required';
$i++;
$modversion['config'][$i]['name'] = 'reqcomments';
$modversion['config'][$i]['title'] = '_KS_REQCOMMENTS';
$modversion['config'][$i]['description'] = '_KS_REQCOMMENTSDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$modversion['config'][$i]['category'] = 'required';
$i++;
$modversion['config'][$i]['name'] = 'colpercat';
$modversion['config'][$i]['title'] = '_KS_COLPERCAT';
$modversion['config'][$i]['description'] = '_KS_COLPERCATDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 3;
$modversion['config'][$i]['category'] = 'layout';
$i++;
$modversion['config'][$i]['name'] = 'groupspecial';
$modversion['config'][$i]['title'] = '_KS_GROUPSPECIALS';
$modversion['config'][$i]['description'] = '_KS_GROUPSPECIALSDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$modversion['config'][$i]['category'] = 'layout';
$i++;
$modversion['config'][$i]['name'] = 'numspecial';
$modversion['config'][$i]['title'] = '_KS_NUMSPECIALS';
$modversion['config'][$i]['description'] = '_KS_NUMSPECIALSDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 3;
$modversion['config'][$i]['category'] = 'layout';
$i++;
$modversion['config'][$i]['name'] = 'rowsperpage';
$modversion['config'][$i]['title'] = '_KS_ROWSPERPAGE';
$modversion['config'][$i]['description'] = '_KS_ROWSPERPAGEDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 3;
$modversion['config'][$i]['category'] = 'layout';
$i++;
$modversion['config'][$i]['name'] = 'acceptterms';
$modversion['config'][$i]['title'] = '_KS_ACCEPTTERMS';
$modversion['config'][$i]['description'] = '_KS_ACCEPTTERMSDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$modversion['config'][$i]['category'] = 'settings';
$i++;
$modversion['config'][$i]['name'] = 'acceptreturn';
$modversion['config'][$i]['title'] = '_KS_ACCEPTRETURN';
$modversion['config'][$i]['description'] = '_KS_ACCEPTRETURNDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$modversion['config'][$i]['category'] = 'settings';
$i++;
$modversion['config'][$i]['name'] = 'showspecial';
$modversion['config'][$i]['title'] = '_KS_SHOWSPECIAL';
$modversion['config'][$i]['description'] = '_KS_SHOWSPECIALDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$modversion['config'][$i]['category'] = 'layout';
$i++;
$modversion['config'][$i]['name'] = 'reqlogin';
$modversion['config'][$i]['title'] = '_KS_REQLOGIN';
$modversion['config'][$i]['description'] = '_KS_REQLOGINDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$modversion['config'][$i]['category'] = 'settings';

$i++;
/**
* Editor to use
*/
$modversion['config'][$i]['name'] = 'editor';
$modversion['config'][$i]['title'] = "_KS_EDITOR";
$modversion['config'][$i]['description'] = '_KS_EDITORDESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['options'] = array(
											'textarea'=>'textarea',
											'dhtml'=>'dhtml',
											'koivi'=>'koivi',
											'tinyeditor'=>'tinyeditor',
											'inbetween'=>'inbetween',
											);
$modversion['config'][$i]['default'] = 'textarea';
$modversion['config'][$i]['category'] = 'layout';
$i++;
$modversion['config'][$i]['name'] = 'thumbw';
$modversion['config'][$i]['title'] = '_KS_THUMBWIDTH';
$modversion['config'][$i]['description'] = '_KS_THUMBWIDTHDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '150';
$modversion['config'][$i]['category'] = 'settings';
$i++;
$modversion['config'][$i]['name'] = 'thumbh';
$modversion['config'][$i]['title'] = '_KS_THUMBHEIGHT';
$modversion['config'][$i]['description'] = '_KS_THUMBHEIGHTDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '150';
$modversion['config'][$i]['category'] = 'settings';
$i++;
$modversion['config'][$i]['name'] = 'thumblib';
$modversion['config'][$i]['title'] = '_KS_THUMBLIB';
$modversion['config'][$i]['description'] = '_KS_THUMBLIBDSC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['options'] = array(
											'GD'=>'GD',
											'ImageMagick'=>'IM',
											'NetPBM'=>'NetPBM',
											);
$modversion['config'][$i]['default'] = 'GD';
$modversion['config'][$i]['category'] = 'settings';
$i++;
$modversion['config'][$i]['name'] = 'thumblibpath';
$modversion['config'][$i]['title'] = '_KS_THUMBLIBPATH';
$modversion['config'][$i]['description'] = '_KS_THUMBLIBPATHDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '/path/my/library';
$modversion['config'][$i]['category'] = 'settings';

?>